## Numpy
- 파이썬의 고성능 과학 계산용 패키지
- matrix, vector와 같은 array 연산의 사실상 표준
- list에 비해 빠르고, 메모리 효율적
- 선형대수와 관련된 다양한 기능 제공
- 반복문 없이 데이터 배열에 대한 처리 지원

## Ndarray
- numpy는 np.array 함수를 사용하여 배열을 생성 -> ndarray
- numpy는 하나의 데이터 type만 배열에 넣을 수 있음
- list와 가장 큰 차이점 -> dynamic type 지원 안함

In [3]:
import numpy as np
a=[1,2,3,4,5]
a=np.array(a,int)
a

array([1, 2, 3, 4, 5])

In [6]:
test_array=np.array(["1","4",5.0,8],float) #float형태로만 형성됨
test_array

array([1., 4., 5., 8.])

In [17]:
a=[1,2,3,4,5]
b=[5,4,3,2,1]
print(a[0] is b[-1]) #a[0]=b[-1]=1

True


In [16]:
a=np.array(a)
b=np.array(b)
print(a[0] is b[-1]) #a[0]=1, b[-1]=1 이 아니라 새로운 메모리 값에 할당..

False


## ndim
- number of dimensions

In [18]:
matrix=[[1,2,5,8],[1,2,5,8],[1,2,5,8]]
np.array(matrix,int).shape #차원

(3, 4)

In [24]:
np.array(matrix,int).ndim

2

## nbytes
-ndarray의 메모리 크기 반환

In [20]:
np.array([[1,2,3],[4,5,6]],dtype=np.float32)

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

In [23]:
np.array([[1,2,3],[4,5,6]],dtype=np.float32).nbytes

24

## reshape
- array의 shape의 크기를 변경, element 갯수는 동일
- -1: size를 기반으로 row 개수 선정 ex)크기가 8일때 reshape(-1,2)면 -1=>4

In [26]:
np.array(matrix).reshape(-1,6)

array([[1, 2, 5, 8, 1, 2],
       [5, 8, 1, 2, 5, 8]])

## slicing
- list와 행과 열 부분을 나눠서 slicing 가능

In [30]:
a=np.array([[1,2,3,4],[1,2,3,4],[1,2,3,4],[1,2,3,4]],int)
print(a[:,2:])


[[3 4]
 [3 4]
 [3 4]
 [3 4]]


In [32]:
a[:,1:3].shape

(4, 2)

## arange
-array 범위를 지정하여 list 생성

In [35]:
np.arange(0,5,0.5)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

## ones, zeros, empty
- ones: 1로만 가득찬 ndarray
- zeros: 0으로만 가득찬 ndarray
- empty: shape만 주어지고 비어있는 ndarray

In [42]:
np.ones((5,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [41]:
np.zeros((5,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [40]:
np.empty(30).reshape(5,6)

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [47]:
#identity: 단위행렬
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [48]:
#eye: 대각선이 1인 행렬
np.eye(5,k=2)

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [50]:
#diag: 대각행렬의 값 추출
matrix=np.arange(9).reshape(3,3)
np.diag(matrix)

array([0, 4, 8])

## numpy.random
- 데이터 분포에 따른 sampling으로 array 생성

In [52]:
np.random.normal(0,1,10).reshape(2,5)

array([[-0.35829749,  0.36209014,  0.26058027, -0.03076008,  0.82265427],
       [-0.02487474,  0.38536426, -0.8985184 , -0.03793677,  0.88247874]])

## operation functions
- sum: ndarray의 elements 간의 합
- axis: 기준이 되는 dimension 축
- mean: 평균
- std: 표준편차
- sqrt: 루트
- concatenate: numpy array를 합치는 함수
- newaxis: 축 늘릴때 사용

In [57]:
a=np.array([[1,2,3]])
b=np.array([[2,3,4]])
np.concatenate((a,b),axis=0)

array([[1, 2, 3],
       [2, 3, 4]])

In [58]:
np.concatenate((a,b),axis=1)

array([[1, 2, 3, 2, 3, 4]])

In [59]:
b=b[np.newaxis,:]
b

array([[[2, 3, 4]]])

## Element-wise operations
- array간 shape가 같을 때 일어나는 연산

In [67]:
test=np.array([[1,2,3],[4,5,6]])

In [68]:
test+test

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [69]:
test*test

array([[ 1,  4,  9],
       [16, 25, 36]])

In [70]:
test.T #전치 행렬

array([[1, 4],
       [2, 5],
       [3, 6]])

In [72]:
#broadcasting 연산
scalar=3
print(test+3)
print(test**2)


[[4 5 6]
 [7 8 9]]
[[ 1  4  9]
 [16 25 36]]


## timeit
- jupyter에서 코드의 퍼포먼스를 체크하는 함수

In [ ]:
def sclar_vector_product(scalar, vector):
    result=[]
    for value in vector:
        result.append(scalar*value)
    return result

vector=list(range(100000000))
scalar=2

%timeit scalar_vector_product(scalar,vector)

## flatten
- 다차원의 array를 1차원으로

In [5]:
import numpy as np
test=np.array([[1,2,3,4],[5,6,7,8]]).flatten()
test

array([1, 2, 3, 4, 5, 6, 7, 8])

## All & Any

In [6]:
a=np.arange(10)
np.any(a>5), np.any(a<0)

(True, False)

In [9]:
np.all(a>5), np.all(a<0)

(False, False)

In [12]:
print(np.logical_and(a>0,a<3))
print(np.logical_not(a)) # 0빼고는 다 false

[False  True  True False False False False False False False]
[ True False False False False False False False False False]


## np.where
- wherer(조건,true, false)

In [13]:
np.where(a>0,3,2) #0일때 빼고는 다 true

array([2, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [14]:
np.where(a>5)

(array([6, 7, 8, 9], dtype=int64),)

## argmax & argmin
- array내 최대, 최소 값

In [15]:
np.argmax(a)

9

In [16]:
np.argmin(a)

0

In [19]:
a.argsort()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int64)

## boolean & fancy index
- 특정 조건에 따른 값을 배열 형태로 추출

In [20]:
test=np.array([1,4,0,2,3,8,9,7],float)
test>3

array([False,  True, False, False, False,  True,  True,  True])

In [21]:
# fancy index: array를 index value로 사용해서 값 추출
a=np.array([2,4,6,8],float)
b=np.array([0,0,1,3,2,1],int)
a[b]

array([2., 2., 4., 8., 6., 4.])

In [23]:
a.take(b) #=a[b]

array([2., 2., 4., 8., 6., 4.])

## loadtxt & savetxt
- text 읽고 저장

In [29]:
a_int=a.astype(int)
a_int_3=a_int[:3]
np.save("npy_test_object",arr=a_int_3)

In [31]:
a_test=np.load(file='npy_test_object.npy')
a_test

array([2, 4, 6])