# 벡터
- 숫자를 원소로 가지는 **리스트 또는 배열**
- 공간에서 한 점
- 원점으로부터 **상대적 위치**
- 벡터에 숫자를 곱해주면 **길이만 변함**
- 벡터끼리 같은 모양을 가지면 **덧셈, 뺄셈, 성분곱** 가능
- 두 벡터의 덧셈은 다른 벡터로부터 **상대적 위치이동**을 표현

In [2]:
import numpy as np
x=np.array([1,7,2])
y=np.array([5,2,1])
print(x+y) #덧셈
print(x-y) #뺄셈
print(x*y) #성분곱

[6 9 3]
[-4  5  1]
[ 5 14  2]


## 벡터의 노름
- 원점에서부터의 거리
- 노름의 종류에 따라 기하학적 성질이 달라짐
- **L1-노름**: 각 성분의 변화량의 절대값의 합
> Robust 학습, Lasso 회귀에 사용
- **L2-노름**: 피타고라스 정리로 계산한 거리
> np.linalg.norm으로도 구현 가능
> 라플라스 근사, Ridge 회귀에 사용

In [3]:
def l1_norm(x):
    x_norm=np.sum(abs(x))
    return x_norm

def l2_norm(x):
    x_norm=np.sum(x*x)
    x_norm=np.sqrt(x_norm)
    return x_norm

## 두 벡터 사이의 각도
- 제2 코사인 법칙으로 계산
- **L2-노름으로만** 가능
- 내적: 정사영의 길이를 벡터 y의 길이만큼 조정한 것
    - 정사영된 벡터의 길이: x의 크기*cos(θ)
    - **두벡터의 유사도 측정**에 사용


In [6]:
#x,y내적/x크기*y크기
def angle(x,y):
    v=np.inner(x,y)/(l2_norm(x)*l2_norm(y)) #제2코사인법칙
    theta=np.arccos(v)
    return theta